slam_toolbox:
  ros__parameters:
    use_sim_time: false
    mode: "mapping"
    slam_toolbox: "sync"

    # Frames
    map_frame: "map"
    odom_frame: "odom"
    base_frame: "base_link"
    scan_topic: "/scan"

    # Map & update
    resolution: 0.03
    max_laser_range: 10.0
    minimum_laser_range: 0.30

    minimum_travel_distance: 0.02
    minimum_travel_heading: 0.02
    transform_publish_period: 0.05
    map_update_interval: 0.1

    scan_queue_size: 10
    throttle_scans: 1

    # Keep it relatively tame
    use_scan_matching: true       # allow some refinement
    do_loop_closing: false        # avoid big jumps for now
    use_pose_extrapolation: false
    enable_interactive_mode: false

